platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example' do
  pod "MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Tests' do
  pod "MWPhotoBrowser", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
end
